### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai202-lukashak#10]
https://drive.google.com/file/d/1Jupr5VQFJpOmHJSJY9Vu2JgmrSXgxk2I/view

**Comment by DanBearLuk** [comment]
**1) Любов.** 

- Людина з самого дитинства формує своє розуміння цього поняття, через що можна сказати, що воно - зрозуміле.
- Так, любов знадобиться кожному, тому вона - цінна.
- Також, любов актуальна, тому що потреба людини у цьому почутті ніколи не зникне.

**2) Мета створення ПП: Допомогти клієнту у побудові стосунків під час підтримання свого фізичного стану, милування архітектурою у сприятливій температурі навколишнього середовища.**

- Перший прецедент: авторизація користувача. Для використання усіх можливостей застосунку, тобто, для забезпечення потреб, що вказані у меті, користувачу необхідно зареєструватися та авторизуватися у застосунку, інакше в нього не буде доступу до всього функціоналу.
- Другий прецедент: перегляд інформації про архітектуру. Одна з потреб, вказаних в меті - милування архітектурою. Для цього й потрібен функціонал з перегляду інформації про навколишню архітектуру.
- Третій прецедент: пошук другої половинки. "Допомогти клієнту у побудові стосунків" - початок мети створення ПП й причина існування третього прецеденту, бо для стосунків потрібно дві людини.

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
